#!/usr/bin/env ruby

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
require 'bundler/setup'
require 'fileutils'
require 'yaml'

class FrontMatterExtractor
    def process lines
      ## read the front matter from the lines
      return reader if lines.empty?
      front_matter = []
      if lines.first.chomp == '---'
        original_lines = lines.dup
        lines.shift
        while !lines.empty? && lines.first.chomp != '---'
          front_matter << lines.shift
        end
  
        return YAML.load(front_matter.join("\n"))
      end

      return {}
    end
  end

class MetadataChecker
    def check front_matter
        errors = []
        unless front_matter.key? "title"
            errors << "title is missing"
        end
        unless front_matter.key? "author"
            errors << "author is missing"
        end
        errors
    end
end

front_matter_extractor = FrontMatterExtractor.new
metadata_checker = MetadataChecker.new

linting_succeeds = true

# Read and print the content of each file passed as arguments
ARGV.each do |file|
  puts "Checking file: #{file}"
  
  begin
    content = File.read(file)
    front_matter = front_matter_extractor.process content.split("\n")
    errors = metadata_checker.check front_matter
    if errors.length() > 0
        puts "Front matter is not valid:\n#{front_matter}"
        puts "Got errors: #{errors}"
        linting_succeeds = false
    end
  rescue => e
    puts "Error reading file #{file}: #{e.message}"
  end
end

exit(linting_succeeds)
